#!/bin/bash
#
# Outputs standard input with environment variables expanded. Handles
# only variables in ${VARNAME} notation.

# See http://stackoverflow.com/a/5274448/1031601
perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg; s/\$\{([^}]+)\}//eg'
