#!/bin/bash
#
# Runs build scripts on the OpenShift instance. At the moment 'git
# push' is the only way to start the build, so artificial change needs
# to be added to the repo (see
# https://bugzilla.redhat.com/show_bug.cgi?id=867965).

SCRIPT_DIR="$(cd "$( dirname "$0" )" && pwd)/"

FORCE_FILE=${SCRIPT_DIR}../.openshift/.force_build

if [[ -n $(git diff) ]]; then
    echo "Uncommitted changes"
    echo "==================="
    git diff
    echo "==================="
    echo ""
    read -p \
        "You have uncommitted changes in the local repository.
 You may want to commit the changes ('git commit') before rebuilding.
 Ignore the changes and continue rebuilding?
 [y/N]
" -n 1 -r
echo

if [[ ! ${REPLY} =~ ^[Yy]$ ]]
then
    exit 0
fi

fi

date > ${FORCE_FILE}
git add ${FORCE_FILE}
git commit -m "Rebuild"

git push origin master