#!/bin/bash
# Helper functions used by several scripts.

export OPENSHIFT_RUN_DIR=${OPENSHIFT_HOMEDIR}/diy-0.1/run/
export OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}/diy-0.1/runtime/
export OPENSHIFT_LOG_DIR=${OPENSHIFT_DIY_LOG_DIR}

VIRTUALENV_DIR=${OPENSHIFT_RUNTIME_DIR}virtualenv/

function activate_virtualenv() {
    echo "Activating virtualenv"
    source ${VIRTUALENV_DIR}bin/activate
    # Use virtualenv directory also for ruby gems.
    export GEM_PATH=""
    export GEM_HOME=${VIRTUALENV_DIR}
}

function is_empty() {
    [[ "$1" == ""  ]]
}

function is_true() {
    [[ "$1" == "1"  ]] || [[ "$1" == "true" ]]
}

function executable_exist() {
    command -v $1 2>&1 >/dev/null
}
