#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Exit on first error.
set -e

source ${OPENSHIFT_REPO_DIR}etc/site.conf
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common

function generate_blog() {
    pushd ${OPENSHIFT_REPO_DIR}blog
    echo "Generating static blog files."
    LC_ALL="en_US.utf8" # Prevents unicode errors.
    tinker --build
    popd
}

if is_true ${TINKERER}; then
    activate_virtualenv
    generate_blog
fi
