#!/bin/bash
# The logic to stop your application should be put in this script.

echo "Stopping nginx."
kill -QUIT `cat ${OPENSHIFT_RUN_DIR}nginx.pid`

echo "Stopping rack for gollum."
kill -INT `cat ${OPENSHIFT_RUN_DIR}gollum.pid`

echo "Stopping uwsgi for wwwhisper."
kill -INT `cat ${OPENSHIFT_RUN_DIR}wwwhisper.pid`
